samplesheet: "config/samples.tsv"

get_genome:
  database: "ncbi"
  assembly: "GCF_000307535.1"
  fasta: Null
  gff: Null
  gff_source_type:
    [
      "RefSeq": "gene",
      "RefSeq": "pseudogene",
      "RefSeq": "CDS",
      "Protein Homology": "CDS",
    ]

processing:
  tool: "fastp"
  fastp:
    extra: ""
  trim_galore:
    extra: "--gzip --paired"
  umi_tools_extract:
    enabled: false # Set to true to enable UMI extraction
    extra: "--bc-pattern=NNNNNNNN --bc-pattern2=NNNNNNNN"

mapping:
  tool: "star"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  star:
    index: ""
    extra: ""
  minimap2:
    index: ""
    extra: "-ax map-ont"
    sorting: "coordinate"
    sort_extra: ""
  samtools_sort:
    extra: "-m 4G"
  samtools_index:
    extra: ""
  samtools_view:
    region: ""
  umi_tools_dedup:
    enabled: false # Set to true to enable deduplication
    extra: "--paired" # or directional, cluster, adjacency, etc.

mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""
  deeptools_coverage:
    genome_size: 1000
    extra: ""

annotation:
  stringtie:
    ref_gtf: ""
    strandedness: ""
    extra: ""

qc:
  multiqc:
    extra: "--verbose --dirs"
  fastqc:
    extra: "--quiet"

report:
  minimum_variant_count: 2
