samplesheet: "config/samples.tsv"

get_genome:
  database: "manual"
  assembly: "KF297339.1"
  fasta: "data/genome/KF297339.1.fasta"
  gff: "data/genome/KF297339.1.gff"
  gff_source_type:
    [
      "Genbank": "gene",
      "Genbank": "pseudogene",
      "Genbank": "CDS",
      "Protein Homology": "CDS",
    ]

processing:
  tool: "fastp"
  fastp:
    extra: ""
  trim_galore:
    extra: "--gzip --paired"
  umi_tools_extract:
    enabled: true # Set to true to enable UMI extraction
    extra: "--bc-pattern=NNNNNNNN --3prime"

mapping:
  tool: "star"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  star:
    index: ""
    extra: ""
  minimap2:
    index: ""
    extra: "-ax map-ont"
    sorting: "coordinate"
    sort_extra: ""
  samtools_sort:
    extra: "-m 4G"
  samtools_index:
    extra: ""
  samtools_view:
    region: ""
  umi_tools_dedup:
    enabled: true # Set to true to enable deduplication
    extra: "" # or directional, cluster, adjacency, etc.

mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""
  deeptools_coverage:
    genome_size: 230000
    extra: "--binSize 10 --normalizeUsing RPKM"

annotation:
  stringtie:
    ref_anno: "data/genome/KF297339.1.gff"
    strandedness: ""
    extra: ""
  gffcompare:
    extra: ""

qc:
  multiqc:
    extra: "--verbose --dirs"
  fastqc:
    extra: "--quiet"

report:
  minimum_variant_count: 2

ucsc_trackhub:
  hub_name: "test"
  email: "aryazand@test.org"
  short_label: "TEST trackhub"
  long_label: "TEST trackhub"
  process_stringtie:
    track_name: "annotation_track_stringtie"
    shortLabel: "annotations from RNA-seq (stringtie)"
    longLabel: "annotations from RNA-seq (stringtie)"
    gtf_to_genePred: ""
    GenePred_to_bgpInput: ""
    bgpInput_to_bigGenePred: "-type=bed12+8 -tab"
  process_gffcompare:
    track_name: "annotation_track_gffcompare"
    shortLabel: "annotations from RNA-seq (gffcompare)"
    longLabel: "annotations from RNA-seq (gffcompare)"
    gtf_to_genePred: ""
    GenePred_to_bgpInput: ""
    bgpInput_to_bigGenePred: "-type=bed12+8 -tab"
  process_genome_annotation:
    gff3_to_GenePred: "-rnaNameAttr=gene" #gff3ToGenePred
    GenePred_to_bgpInput: "" #genePredToBigGenePred
    bgpInput_to_bigGenePred: "-type=bed12+8 -tab" #bedToBigBed
  process_fasta:
    faToTwoBit: ""
  process_bw:
    plus_color: "0,0,100"
    minus_color: "255,0,0"
    negateValues_for_minus_strand: "on" # on or off
  genomes:
    KF297339.1:
      defaultPos: "KF297339.1:1-20000"
      organism: "Human Cytomegalovirus"
      scientificName: "Human Herpesvirus 5 strain TB40E"
      description: "HCMV TB40E, clone Lisa"
      html_string: "HCMV TB40E, clone Lisa (html string)"
      annotation:
        track_name: "TB40"
        short_label: "HCMV TB40E"
        long_label: "HCMV TB40E, clone Lisa"
